server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # 当前微服务不注册到eureka中(消费端)
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000