spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/cnative_logistics?useUnicode=true&character_set_server=utf8mb4&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      idle-timeout: 180000
      connection-test-query: select 1

    type: com.zaxxer.hikari.HikariDataSource