server:
  port: 8887

spring:
  application:
    name: config-service
  cloud:
   config:
     server:
       git:
        uri: https://gitee.com/yeAllen/CloudNativeDemo.git
        skipSslValidation: true
        search-paths: 'Config/{profile}/{application}'

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/